gradle: update dependencies
dkhmelenko/miband-android pull request #6
Opened 2018-12-30 06:11 UTC by SubhrajyotiSen

remove retrolambda as it is no longer needed

2018-12-30 23:27 UTC, dkhmelenko requested changes

2018-12-30 23:27 UTC, dkhmelenko commented on app/build.gradle
> -    implementation "io.reactivex:rxandroid:$libraries.rxAndroid"
We need to keep RxAndroid dependency.

2018-12-30 23:27 UTC, dkhmelenko commented on miband-sdk/build.gradle
> -    implementation "io.reactivex:rxandroid:$libraries.rxAndroid"
We need to keep RxAndroid

2018-12-30 23:27 UTC, dkhmelenko commented on miband-sdk/build.gradle
> +    implementation "io.reactivex.rxjava2:rxandroid:$libraries.rxAndroid"
This entry duplicates previous one

2018-12-31 04:13 UTC, SubhrajyotiSen commented on app/build.gradle
> -    implementation "io.reactivex:rxandroid:$libraries.rxAndroid"
I haven't removed RxAndroid. According to their docs, the complete dependency name is `io.reactivex.rxjava2:rxandroid` and not `io.reactivex:rxandroid`. I just updated that

2019-01-01 13:43 UTC, dkhmelenko approved these changes

2019-01-01 13:43 UTC, merged